CI-prod: mount the host's output/ dir to docker's output/ dir to upload artifacts later

diff --git a/.github/workflows/CI-production-testing.yml b/.github/workflows/CI-production-testing.yml
--- a/.github/workflows/CI-production-testing.yml
+++ b/.github/workflows/CI-production-testing.yml
@@ -66,7 +66,14 @@ jobs:
     - name: Config file tests
       run: python3 -m pytest -s tests/integration_tests/test_config_files.py -n 2 -p no:warnings -vv
 
-     #Reaching this step means all unit tests passed out side of docker
+    - name: Upload Artifact
+      # run this job whether the above jobs failed or passed
+      if: success() || failure()
+      uses: actions/upload-artifact@v3
+      with:
+        name: test_slips_locally-integration-tests-output
+        path: |
+          output/integration_tests
 
   test_slips_in_docker:
     # runs the tests in a docker(built by this job) on stop of a GH VM
@@ -74,7 +81,7 @@ jobs:
     # 2 hours timeout
     timeout-minutes: 7200
     env:
-      SLIPS_VERSION: v1.0.2
+      SLIPS_VERSION: v1.0.2 #TODO update this
 
     strategy:
       matrix:
@@ -84,6 +91,7 @@ jobs:
             image_name: slips
             path: ./docker/ubuntu-image/Dockerfile
 #
+#         #TODO our unit tests dont support macos yet
 #          - type: macosm1-image
 #            name: macosm1-image
 #            image_name: slips_macos_m1
@@ -111,20 +119,30 @@ jobs:
     # use the built image to run unit tests inside docker
     # we ignore the blocking module unit tests because we cannot run
     # docker with -cap-add=NET_ADMIN and use iptables in GH actions
-    - name: Run unit tests inside docker
+    - name: Run tests inside docker
       uses: addnab/docker-run-action@v3
       with:
         image: stratosphereips/slips:latest
+        # mount the host's output/ dir to docker's output/ dir, the goal is to access integration
+        # tests output in docker from the host to upload it later
+        options: -v ${{ github.workspace }}/output:/StratosphereLinuxIPS/output
         run: |
           git reset --hard
           git pull & git checkout origin/develop
-          python3 -m pip install -r requirements.txt 
           redis-server --daemonize yes
-          git show-branch --no-name HEAD
           python3  -m pytest tests/ --ignore="tests/test_daemon.py" --ignore="tests/test_database.py" --ignore="tests/integration_tests" -n 7 -p no:warnings -vv -s
           python3  -m pytest tests/test_database.py -p no:warnings -vv
           python3  -m pytest tests/test_daemon.py -p no:warnings -vv
           printf "0" | ./slips.py -k
           python3 -m pytest -s tests/integration_tests/test_dataset.py -n 4 -p no:warnings -vv
           python3 -m pytest -s tests/integration_tests/test_config_files.py -n 2 -p no:warnings -vv
+
+    - name: Upload Artifact
+      # run this job whether the above jobs failed or passed
+      if: success() || failure()
+      uses: actions/upload-artifact@v3
+      with:
+        name: test_slips_in_docker-integration-tests-output
+        path: |
+          ${{ github.workspace }}/output/integration_tests
 
